apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik_deployment
  namespace: kube-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik_deployment
  template:
    metadata:
      labels:
        app: traefik_deployment
    spec:
      restartPolicy: Always
      containers:
      - name: traefik_deployment
        image: traefik:1.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
