apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: kube-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik-deployment
  template:
    metadata:
      labels:
        app: traefik-deployment
    spec:
      restartPolicy: Always
      containers:
      - name: traefik-deployment
        image: traefik:1.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
